name: Deploy

on: 
  push:
    branches:
      - master

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
 first_job:
  runs-on: ubuntu-latest
  concurrency:
    group: example-${{ github.ref }}
    cancel-in-progress: true

  steps:
   - name: getnvm
     uses: dcodeIO/setup-node-nvm@master
     with:
       node-version: lts/*

   - name: checkout
     uses: actions/checkout@v4

   - name: caching
     uses: actions/cache@v4
     with:
       path: pages/node_modules
       key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

   - name: prepare
     run: |
          cd pages
          npm install -g @angular/cli
          npm install
          npm run build -- --base-href https://${{ github.actor }}.github.io/${{ github.event.repository.name }}/

   - name: Save in Artifact
     uses: actions/upload-artifact@4
     with: 
      name: build-page-${{ github.actor }}
      path: pages/dist/pages

 second_job_deploy:
  needs: first_job
  if: success()
  runs-on: ubuntu-latest
  concurrency:
    group: deploy-${{ github.ref }}
    cancel-in-progress: true

  steps:

   - name: checkout
     uses: actions/checkout@v4
     
   - name: get artifact  
     uses: actions/download-artifact@v4.6.2
     with:
       name: build-page-${{ github.actor }}
       path: pages/dist/pages
     
   - name: Deploy
     if: success()
     uses: actions/upload-pages-artifact@v3.0.1
     with:
      name: ${{ github.actor }}
      publish_dir: pages/dist/pages/browser
   
   - name: finished
     run: echo "### DEPLOYED ::rocket::" >> $GITHUB_STEP_SUMMARY
    
       
