name: Deploy

on: 
  push:
    branches:
      - master

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
 first_job:
  runs-on: ubuntu-latest

  steps:
   - name: getnvm
     uses: dcodeIO/setup-node-nvm@master
     with:
       node-version: lts/*

   - name: checkout
     uses: actions/checkout@v4

   - name: prepare
     run: |
          cd pages
          npm install -g @angular/cli
          npm install
          npm run build -- --base-href https://${{ github.actor }}.github.io/${{ github.event.repository.name }}/

   - name: Deploy
     if: success()
     uses: peaceiris/actions-gh-pages@v3
     with:
       github_token: ${{ secrets.GITHUB_TOKEN }}
       publish_dir: pages/dist/pages/browser
       enable_jekyll: true
   
   - name: finished
     run: echo "### DEPLOYED :::rocket:::" >> $GITHUB_STEP_SUMMARY
    
       
