name: Deploy

on: 
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
 
 build-pages:
  runs-on: ubuntu-latest
  concurrency:
    group: example-${{ github.ref }}
    cancel-in-progress: true

  steps:

   - name: checkout
     uses: actions/checkout@v4
   
   - name: get Node
     uses: actions/setup-node@4.4.0
     with:
       node-version: lts/*

   - name: caching
     uses: actions/cache@v4
     with:
       path: pages/node_modules
       key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

   - name: prepare
     run: |
          cd pages
          npm install -g @angular/cli
          npm install
          npm run build

   - name: Remove symlinks before upload
     run: find pages/dist/pages/browser/ -type l -delete

   - name: Save in Artifact
     uses: actions/upload-pages-artifact@v3
     with: 
      path: pages/dist/pages/
   
 deploy-pages:
 
  needs:  build-pages
  permissions:
   contents: write
   pages: write
   id-token: write
  
  if: success()
  
  runs-on: ubuntu-latest
  environment: PROD
    
  concurrency:
    group: prepare-${{ github.ref }}
    cancel-in-progress: true

  steps:

   - name: deploy to github pages
     uses: actions/deploy-pages@v4
    
   - name: finished
     run: echo "### DEPLOYED ::rocket::" >> $GITHUB_STEP_SUMMARY
