name: Deploy

on: 
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
 
 build-pages:
  runs-on: ubuntu-latest
  concurrency:
    group: example-${{ github.ref }}
    cancel-in-progress: true

  steps:

   - name: checkout
     uses: actions/checkout@v4
   
   - name: get Node
     uses: actions/setup-node@4.4.0
     with:
       node-version: 22

   - name: caching
     uses: actions/cache@v4
     with:
       path: pages/node_modules
       key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

   - name: prepare
     run: |
          cd pages
          npm install -g @angular/cli
          npm install
          npm run build -- --base-href https://${{ github.actor }}.github.io/${{ github.event.repository.name }}/

   - name: Save in Artifact
     uses: actions/upload-artifact@4.6.2
     with: 
      name: build-page-${{ github.actor }}
      path: pages/dist/pages

 prepared-artifact-pages:
  needs: build-pages
  if: success()
  runs-on: ubuntu-latest
  concurrency:
    group: prepare-${{ github.ref }}
    cancel-in-progress: true

  steps:

   - name: checkout
     uses: actions/checkout@v4
     
   - name: get artifact  
     uses: actions/download-artifact@v4.3.0
     with:
       name: build-page-${{ github.actor }}
       path: pages/dist/pages
     
   - name: Upload Artifact Pages
     if: success()
     uses: actions/upload-pages-artifact@v3.0.1
     with:
      name: ${{ github.actor }}-pages
      path: pages/dist/pages/browser
   
 deploy-pages:
 
  needs:  prepared-artifact-pages
  permissions:
   contents: write
   pages: write
   id-token: write
  
  if: success()
  
  runs-on: ubuntu-latest
  
  concurrency:
    group: prepare-${{ github.ref }}
    cancel-in-progress: true

  environment:
   name: github-pages

  steps:

   - name: deploy to github pages
     uses: actions/deploy-pages@v4
     with:
      artifact_name: ${{ github.actor }}-pages
    
   - name: finished
     run: echo "### DEPLOYED ::rocket::" >> $GITHUB_STEP_SUMMARY
